### PR TITLE
Add support for in-memory database

### PR DESCRIPTION
**Pull request by johan12345**
E.g. for unit testing purposes it is often useful to be able to create an in-memory database with [`Room.inMemoryDatabaseBuilder`](https://developer.android.com/reference/androidx/room/Room#inMemoryDatabaseBuilder(android.content.Context,java.lang.Class)). This PR adds a corresponding `SpatiaRoom.inMemoryDatabaseBuilder` function for doing the same with spatia-room.

Apparently in-memory databases cannot be created from an asset, so I needed to remove `createFromAsset(templateDb)` call and the `spatia_db_template.sqlite` file. Instead, I added a callback that calls `SELECT InitSpatialMetaData();` to initialize the database, which should have the same effect (right?) and also removes the need for shipping this extra 5 MB file with the app.

### CODE REVIEW

**Comment by dalgarins** [comment]
Hi @johan12345 this is great, I'm going to test it.

**Comment by dalgarins** [comment]
I'll let you know when the release has this changes.

**Comment by dalgarins** [comment]
@johan12345 here is the new version:  

`implementation 'com.github.anboralabs:spatia-room:0.2.6'`

**Comment by johan12345** [comment]
Awesome, thanks!

**Pull request merged**
